# Discovery Service
discovery:
  replicaCount: 1
  image:
    repository: "zeinebmessaoudi/discovery"
    tag: "v96"
    pullPolicy: IfNotPresent
  service:
    port: 8761
    targetPort: 8761
    type: NodePort
  env:
    SPRING_PROFILES_ACTIVE: docker
    MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
    MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
# Gateway Service
gateway:
  replicaCount: 1
  image:
    repository: "zeinebmessaoudi/gateway"
    tag: "v98"
    pullPolicy: IfNotPresent
  service:
    port: 8222
    targetPort: 8222
    type: NodePort
  env:
    SPRING_PROFILES_ACTIVE: docker
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
    MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
# Customer Service
customer:
  replicaCount: 1
  image:
    repository: "zeinebmessaoudi/customer"
    tag: "v96"
    pullPolicy: IfNotPresent
  service:
    port: 8090
    targetPort: 8090
    type: ClusterIP
  env:
    SPRING_PROFILES_ACTIVE: docker
    MONGO_INITDB_ROOT_USERNAME: alibou
    MONGO_INITDB_ROOT_PASSWORD: alibou
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
    MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
# MailDev
mailDev:
  replicaCount: 1
  image:
    repository: docker.io/zeinebmessaoudi/maildev
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    ports:
      http:
        port: 1080
        targetPort: 1080
        nodePort: 31080
      smtp:
        port: 1025
        targetPort: 1025
        nodePort: 31025
postgresql:
  replicas: 1
  image:
    repository: docker.io/zeinebmessaoudi/postgres
    tag: latest
  env:
    POSTGRES_USER_SECRET_NAME: postgres-secret
    POSTGRES_USER_SECRET_KEY: POSTGRES_USER
    POSTGRES_PASSWORD_SECRET_NAME: postgres-secret
    POSTGRES_PASSWORD_SECRET_KEY: POSTGRES_PASSWORD
    PGDATA_CONFIGMAP_NAME: postgres-config
    PGDATA_CONFIGMAP_KEY: PGDATA
  volumeMounts:
    mountPath: /data/postgres
  service:
    port: 5432
    targetPort: 5432
    type: ClusterIP
product:
  replicaCount: 1
  image:
    repository: "zeinebmessaoudi/customer"
    tag: "v97"
    pullPolicy: IfNotPresent
  service:
    port: 8050
    targetPort: 8050
    type: ClusterIP
  env:
    SPRING_PROFILES_ACTIVE: docker
    SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/product
    SPRING_DATASOURCE_USERNAME: alibou
    SPRING_DATASOURCE_PASSWORD: alibou
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
    MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
# MongoDB Configuration and Secret
configMap:
  name: mongo-config
  ME_CONFIG_MONGODB_SERVER: mongodb
  name: postgres-config
  PGDATA: /data/postgres
secret:
  name: mongodb-secret
  MONGO_INITDB_ROOT_USERNAME: alibou
  MONGO_INITDB_ROOT_PASSWORD: alibou
  name: postgres-secret
  POSTGRES_USER: alibou
  POSTGRES_PASSWORD: alibou
# Mongo Express
mongoExpress:
  replicaCount: 1
  image:
    repository: docker.io/zeinebmessaoudi/mongo-express
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 8081
    targetPort: 8081
    type: NodePort
  env:
    configMapName: mongo-config
    secretName: mongodb-secret
    adminUsernameKey: MONGO_INITDB_ROOT_USERNAME
    adminPasswordKey: MONGO_INITDB_ROOT_PASSWORD
    mongoServerKey: ME_CONFIG_MONGODB_SERVER
# MongoDB
mongodb:
  replicaCount: 1
  image:
    repository: docker.io/zeinebmessaoudi/mongo
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 27017
    targetPort: 27017
    type: ClusterIP
  env:
    secretName: mongodb-secret
    usernameKey: MONGO_INITDB_ROOT_USERNAME
    passwordKey: MONGO_INITDB_ROOT_PASSWORD
  persistence:
    enabled: false
    mountPath: /data
# Notification Service
notification:
  replicaCount: 1
  image:
    repository: "zeinebmessaoudi/notification"
    tag: "v98"
    pullPolicy: IfNotPresent
  service:
    port: 8040
    targetPort: 8040
    type: ClusterIP
  env:
    SPRING_PROFILES_ACTIVE: docker
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    SPRING_DATA_MONGODB_USERNAME: alibou
    SPRING_DATA_MONGODB_PASSWORD: alibou
    SPRING_DATA_MONGODB_HOST: mongodb
    SPRING_DATA_MONGODB_PORT: "27017"
    SPRING_DATA_MONGODB_DATABASE: notification
    SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
    SPRING_MAIL_HOST: mail-dev
    SPRING_MAIL_PORT: "1025"
    SPRING_MAIL_USERNAME: alibou
    SPRING_MAIL_PASSWORD: aliboudocker rm
    SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS: "kafka-service:9092"
    MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
    MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
    SPRING_KAFKA_CONSUMER_GROUP_ID: "paymentGroup,orderGroup"
    SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET: "earliest"
# Order Service
order:
  replicaCount: 1
  image:
    repository: "zeinebmessaoudi/order"
    tag: "v98"
    pullPolicy: IfNotPresent
  service:
    port: 8070
    targetPort: 8070
    type: ClusterIP
  env:
    SPRING_PROFILES_ACTIVE: docker
    SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/order
    SPRING_DATASOURCE_USERNAME: alibou
    SPRING_DATASOURCE_PASSWORD: alibou
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
    MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
    MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
# Payment Service
payment:
  replicaCount: 1
  image:
    repository: "zeinebmessaoudi/payment"
    tag: "v98"
    pullPolicy: IfNotPresent
  service:
    port: 8060
    targetPort: 8060
    type: ClusterIP
  env:
    SPRING_PROFILES_ACTIVE: docker
    SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/payment
    SPRING_DATASOURCE_USERNAME: alibou
    SPRING_DATASOURCE_PASSWORD: alibou
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
    MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
    MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
# Zipkin
zipkin:
  replicaCount: 1
  image:
    repository: docker.io/zeinebmessaoudi/zipkin
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 9411
    targetPort: 9411
    type: NodePort
