apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: gmail-notifications
  namespace: monitoring
  labels:
    release: kube-prometheus-stack  
spec:
  route:
    receiver: "null"
    groupBy:
    - alertname
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 1h
    routes:
    - receiver: "gmail"
      matchers:
      - 'namespace="default"'
      groupWait: 30s
      groupInterval: 5m
      repeatInterval: 1h

  receivers:
  - name: "null"
  - name: "gmail"
    emailConfigs:
    - to: "zeineb.messaoudi@etudiant-enit.utm.tn"
      from: "zeineb.messaoudi@etudiant-enit.utm.tn"
      smarthost: "smtp.gmail.com:587"
      authUsername: "zeineb.messaoudi@etudiant-enit.utm.tn"
      authPassword:
        name: smtp-credentials
        key: password
      requireTLS: true
      sendResolved: true


