apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: gmail-notifications
  namespace: monitoring
  labels:
    alertmanagerConfig: gmail-notifications
spec:
  route:
    receiver: gmail
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 1h

  receivers:
    - name: gmail
      emailConfigs:
        - to: "zeineb.messaoudi@etudiant-enit.utm.tn"
          from: "zeineb.messaoudi@etudiant-enit.utm.tn"
          smarthost: "smtp.gmail.com:587"
          authUsername: "zeineb.messaoudi@etudiant-enit.utm.tn"
          authPassword:
            name: smtp-credentials
            key: password
          requireTLS: true
          sendResolved: true

