apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: gmail-notifications
  namespace: monitoring
  labels:
    alertmanagerConfig: gmail-notifications
spec:
  route:
    receiver: gmail
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 12h
  receivers:
  - name: gmail
    emailConfigs:
    - to:       'zeineb.messaoudi@etudiant-enit.utm.tn'      
      from:     'alertmanager@gmail.com'      
      authUsername: 'zeineb.messaoudi@etudiant-enit.utm.tn'     
      authPassword:
        name: alertmanager-gmail-secret
        key: password
      requireTLS: true
      smarthost:  'smtp.gmail.com:587'
