apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: gmail-notifications
  namespace: monitoring
  labels:
    alertmanagerConfig: gmail-notifications
spec:
  route:
    receiver: 'gmail'
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 1h

  receivers:
  - name: 'gmail'
    emailConfigs:
    - to: 'zeineb.messaoudi@etudiant-enit.utm.tn'
      from: 'zeineb.messaoudi@etudiant-enit.utm.tn'
      smarthost: 'smtp.gmail.com:587'
      authUsername: 'zeineb.messaoudi@etudiant-enit.utm.tn'
      authPassword: 'itxm retw owdw dzun'
      requireTLS: true
      sendResolved: true
