apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-dev
spec:
  replicas: {{ .Values.mailDev.replicaCount }}
  selector:
    matchLabels:
      app: mail-dev
  template:
    metadata:
      labels:
        app: mail-dev
    spec:
      containers:
        - name: mail-container
          image: {{ .Values.mailDev.image.repository }}:{{ .Values.mailDev.image.tag }}
          imagePullPolicy: {{ .Values.mailDev.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.mailDev.service.ports.http.targetPort }}
            - containerPort: {{ .Values.mailDev.service.ports.smtp.targetPort }}
      imagePullSecrets:
            - name: harbor-secret  


---

apiVersion: v1
kind: Service
metadata:
  name: mail-dev-service
spec:
  selector:
    app: mail-dev
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.mailDev.service.ports.http.port }}
      targetPort: {{ .Values.mailDev.service.ports.http.targetPort }}
      nodePort: {{ .Values.mailDev.service.ports.http.nodePort }}
    - name: smtp
      protocol: TCP
      port: {{ .Values.mailDev.service.ports.smtp.port }}
      targetPort: {{ .Values.mailDev.service.ports.smtp.targetPort }}
      nodePort: {{ .Values.mailDev.service.ports.smtp.nodePort }}
  type: {{ .Values.mailDev.service.type }}

