apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: notification
spec:
  replicas: {{ .Values.notification.replicaCount }}
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: "/actuator/prometheus"
      prometheus.io/port: "8040"           
    spec:
      containers:
        - name: notification-container
          image: "{{ .Values.notification.image.repository }}:{{ .Values.notification.image.tag }}"
          imagePullPolicy: {{ .Values.notification.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.notification.service.targetPort }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .Values.notification.env.SPRING_PROFILES_ACTIVE }}"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "{{ .Values.notification.env.EUREKA_CLIENT_SERVICEURL_DEFAULTZONE }}"
            - name: SPRING_DATA_MONGODB_USERNAME
              value: "{{ .Values.notification.env.SPRING_DATA_MONGODB_USERNAME }}"
            - name: SPRING_DATA_MONGODB_PASSWORD
              value: "{{ .Values.notification.env.SPRING_DATA_MONGODB_PASSWORD }}"
            - name: SPRING_DATA_MONGODB_HOST
              value: "{{ .Values.notification.env.SPRING_DATA_MONGODB_HOST }}"
            - name: SPRING_DATA_MONGODB_PORT
              value: "{{ .Values.notification.env.SPRING_DATA_MONGODB_PORT }}"
            - name: SPRING_DATA_MONGODB_DATABASE
              value: "{{ .Values.notification.env.SPRING_DATA_MONGODB_DATABASE }}"
            - name: SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE
              value: "{{ .Values.notification.env.SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE }}"
            - name: SPRING_MAIL_HOST
              value: "{{ .Values.notification.env.SPRING_MAIL_HOST }}"
            - name: SPRING_MAIL_PORT
              value: "{{ .Values.notification.env.SPRING_MAIL_PORT }}"
            - name: SPRING_MAIL_USERNAME
              value: "{{ .Values.notification.env.SPRING_MAIL_USERNAME }}"
            - name: SPRING_MAIL_PASSWORD
              value: "{{ .Values.notification.env.SPRING_MAIL_PASSWORD }}"
            - name: SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS
              value: "{{ .Values.notification.env.SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS }}"
            - name: MANAGEMENT_TRACING_SAMPLING_PROBABILITY
              value: "{{ .Values.notification.env.MANAGEMENT_TRACING_SAMPLING_PROBABILITY }}"
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: "{{ .Values.notification.env.MANAGEMENT_ZIPKIN_TRACING_ENDPOINT }}" 
            - name: SPRING_KAFKA_CONSUMER_GROUP_ID
              value: "{{ .Values.notification.env.SPRING_KAFKA_CONSUMER_GROUP_ID }}"             
            - name: SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET
              value: "{{ .Values.notification.env.SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET }}"                  
      imagePullSecrets:
            - name: harbor-secret                
---

apiVersion: v1
kind: Service
metadata:
  name: notification
spec:
  selector:
    app: notification
  ports:
    - name: http
      port: {{ .Values.notification.service.port}}
      targetPort: {{ .Values.notification.service.targetPort}}
  type: {{ .Values.notification.service.type}}
