apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
spec:
  replicas: {{ .Values.order.replicaCount }}
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order-container
          image: {{ .Values.order.image.repository }}:{{ .Values.order.image.tag }}
          imagePullPolicy: {{ .Values.order.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.order.service.targetPort }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .Values.order.env.SPRING_PROFILES_ACTIVE }}"
            - name: SPRING_DATASOURCE_URL
              value: "{{ .Values.order.env.SPRING_DATASOURCE_URL }}"
            - name: SPRING_DATASOURCE_USERNAME
              value: "{{ .Values.order.env.SPRING_DATASOURCE_USERNAME }}"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "{{ .Values.order.env.SPRING_DATASOURCE_PASSWORD }}"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "{{ .Values.order.env.EUREKA_CLIENT_SERVICEURL_DEFAULTZONE }}"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "{{ .Values.order.env.SPRING_KAFKA_BOOTSTRAP_SERVERS }}"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "{{ .Values.order.env.KAFKA_BOOTSTRAP_SERVERS }}"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "{{ .Values.order.env.KAFKA_ADVERTISED_LISTENERS }}"
            - name: MANAGEMENT_TRACING_SAMPLING_PROBABILITY
              value: "{{ .Values.order.env.MANAGEMENT_TRACING_SAMPLING_PROBABILITY }}"
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: "{{ .Values.order.env.MANAGEMENT_ZIPKIN_TRACING_ENDPOINT }}"
      imagePullSecrets:
            - name: harbor-secret              
---
apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: default  
spec:
  selector:
    app: order
  ports:
    - protocol: TCP
      port: {{ .Values.order.service.Port | default 8080}}
      targetPort: {{ .Values.order.service.targetPort | default 8080 }}
  type: {{ .Values.order.service.type }}
