apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: {{ .Values.postgres.replicaCount }}
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres-container
          image: {{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}
          ports:
            - containerPort: {{ .Values.postgres.service.targetPort }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.env.POSTGRES_USER_SECRET_NAME }}
                  key: {{ .Values.postgres.env.POSTGRES_USER_SECRET_KEY }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.env.POSTGRES_PASSWORD_SECRET_NAME }}
                  key: {{ .Values.postgres.env.POSTGRES_PASSWORD_SECRET_KEY }}
            - name: PGDATA
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.postgres.env.PGDATA_CONFIGMAP_NAME }}
                  key: {{ .Values.postgres.env.PGDATA_CONFIGMAP_KEY }}
          volumeMounts:
            - mountPath: {{ .Values.postgres.volumeMounts.mountPath }}
      imagePullSecrets:
            - name: harbor-secret            
---

apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.service.Port | default 8080 }}
      targetPort: {{ .Values.postgres.service.targetPort | default 8080 }}
  type: {{ .Values.postgres.service.type }}
