apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgresql
spec:
  replicas: {{ .Values.postgresql.replicaCount }}
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgres-container
          image: {{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}
          ports:
            - containerPort: {{ .Values.postgresql.service.targetPort }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.env.POSTGRES_USER_SECRET_NAME }}
                  key: {{ .Values.postgresql.env.POSTGRES_USER_SECRET_KEY }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.env.POSTGRES_PASSWORD_SECRET_NAME }}
                  key: {{ .Values.postgresql.env.POSTGRES_PASSWORD_SECRET_KEY }}
            - name: PGDATA
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.postgresql.env.PGDATA_CONFIGMAP_NAME }}
                  key: {{ .Values.postgresql.env.PGDATA_CONFIGMAP_KEY }}
          volumeMounts:
            - name: postgres
              mountPath: /data/postgres
      volumes:
        - name: postgres
          emptyDir: {}
      imagePullSecrets:
            - name: harbor-secret            
---

apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
spec:
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: {{ .Values.postgresql.service.port}}
      targetPort: {{ .Values.postgresql.service.targetPort}}
  type: {{ .Values.postgresql.service.type }}
