apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: product
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: product
  namespaceSelector:
    matchNames:
      - default        
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s

