apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: {{ .Values.zookeeper.replicaCount }}
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper-container
          image: {{ .Values.zookeeper.image.repository }}:{{ .Values.zookeeper.image.tag }}
          imagePullPolicy: {{ .Values.zookeeper.image.pullPolicy }}
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "{{ .Values.zookeeper.env.ZOOKEEPER_CLIENT_PORT }}"
            - name: ZOOKEEPER_TICK_TIME
              value: "{{ .Values.zookeeper.env.ZOOKEEPER_TICK_TIME }}"
          ports:
            - containerPort: {{ .Values.zookeeper.service.targetPort }}
      imagePullSecrets:
        - name: harbor-secret
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: {{ .Values.zookeeper.service.port }}
      targetPort: {{ .Values.zookeeper.service.targetPort }}
  type: {{ .Values.zookeeper.service.type }}
